[project]
name = "hyperparameter-tuning-search-project"
version = "0.1.0"
description = "hyperparameter optimization with metaheuristic algorithms"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.2.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
